### ISSUE TITLE
base64 in rust vs browser's built-in

### ISSUE THREAD

**Issue by marshallpierce** [badboy/hellorust#10]
I'm not sure if this is the sort of demo you're interested in, but I threw [this](https://bitbucket.org/marshallpierce/rust-wasm-base64) together and was pleasantly surprised by how good the performance of the wasm'd rust was. On my machines, it's several times faster, with the lead increasing as input sizes grow. Firefox's wasm runtime seems a step ahead of Chrome's, also.

**Comment by badboy** [comment]
Cool! That’s definitely right to put on here. 
If you’re okay with it I pull it in as a new example and name you as the author. Of course I‘d welcome it as a Pull Request by you as well.

**Comment by marshallpierce** [comment]
Sure, feel free to turn it into an example. I'll PR it if you don't get around to it but it'll be a few days at least until I'll have time.

**Comment by badboy** [comment]
Hey @marshallpierce.
Sorry for not implementing this yet. If I integrate the example, would it be ok to CC0-license it? (Change proposed here: https://github.com/badboy/hellorust/issues/23)

**Comment by marshallpierce** [comment]
Sure, that's fine with me. I'll apply CC0 to the demo.

Edit: Done - https://bitbucket.org/marshallpierce/rust-wasm-base64/commits/43a158dd19576edd6cb65a7f15b740a0717f8e69

**Comment by badboy** [comment]
Cool, thanks! Will add it over the weekend.
