### ISSUE TITLE
Faults in the setup/wasm-target guide

### ISSUE THREAD

**Issue by NoHatCoder** [badboy/hellorust#11]
I tried to follow this guide, but it seems to have some issues.

First "rustup update" will only update what is already installed, if the correct (platform dependent) nightly toolchain hasn't already been installed this won't do the trick, so next step will fail.

~Second, rustc does not seem to recognise +nightly as a command, I haven't figured what the right thing to put instead is, so this is where I'm stuck.~

Ok, that was a messup with two different installs, looks like I got it working.

I'm on 64-bit Windows 7 by the way.

**Comment by badboy** [comment]
Right, I should mention how to install nightly. Will change that in a second.
The `+nightly` shortcut is handled by the wrappers around `rustc` and `cargo` installed by rustup.
