### ISSUE TITLE
Sha1 demo is broken

### ISSUE THREAD

**Issue by alakhtikov** [badboy/hellorust#16]
Hi!

Thank you for the site.
https://www.hellorust.com/demos/sha1/index.html demo doesn't work. Digest is always "Digest will be shown here" regardless of input. Tried FF + win10, Chrome + MacOS.

http://webassembly.org/demo/Tanks/ works fine.

**Comment by badboy** [comment]
Nice, I managed to break it and not test it. Sorry about that, fixing now.
