### ISSUE TITLE
Demos should use extern fn?

### ISSUE THREAD

**Issue by starwed** [badboy/hellorust#19]
I think that the various [demos](https://www.hellorust.com/demos/add/index.html) here should declare the exported functions with `extern` -- at any rate, I needed to do so to get a minimal example working when built with cargo, after following the setup instructions [here](https://www.hellorust.com/setup/wasm-target/).

**Comment by badboy** [comment]
Yes, as mentioned on Twitter before these work more or less "by accident". I just didn't sit for long enough infront of my computer to fix them. I might get around it tomorrow.
