### ISSUE TITLE
Integer overflow in factorial demo

### ISSUE THREAD

**Issue by matprec** [badboy/hellorust#2]
Currently, the value is [stored as an i32](https://github.com/badboy/hellorust/blob/master/demos/factorial/factorial.rs#L4). It can only hold values from ~±2*10^10, hence store factorials <= fact(12). Everything above will overflow. This can be observed by the naked eye when computing factorial 17 and 18, as they'll go negative :D

I see two options - use an i64 as datatype or restrict to factorials <=12 instead of 20.

**Comment by badboy** [comment]
Thanks for coming here.
Right now that's intentional (though I should add a paragraph explaining that).
In order to use i64 we need to do the string formatting on the Rust side as well (as JavaScript doesn't have i64 at all). I will hopefully get to it next week.

**Comment by badboy** [comment]
Oh, I already fixed that last week: https://github.com/badboy/hellorust/commit/3b0d1c9259c0e39a481b51764b053520b7a2fbd1
