### ISSUE TITLE
A new example on how to work with the imported memory

### ISSUE THREAD

**Issue by daniel-abramov** [badboy/hellorust#20]
It would be nice to update the example which shows the usage of imported memory and show how to use it for passing arrays into webassembly and getting the result back. Would be an interesting and useful example I think (quite a common use case).

It's clear that the one can simply export `alloc()` and `dealloc()` functions from Rust and then use them in JavaScript to allocate memory, fill it and pass the pointer to Rust, but it would be also interesting to see how to do the same with the imported memory (I believe in this case it saves the caller from explicitly calling `alloc()` function, but I'm not sure about that)

**Comment by badboy** [comment]
A new example showing how to actual use the memory could be interesting for sure.
We have to be careful though, mixing two allocators (one on each side) will most likely lead to problems, so we have several possibilities:
1. Have the same allocator on both sides
2. Have just one allocator and the other side has to call into it (as we currently do with the allocator in Rust)
3. Don't allocate on the Rust side, then we can just put stuff into memory once and Rust can use it

For the example I can go with option 3 for now.

**Comment by daniel-abramov** [comment]
Sounds good!

By option (3) you basically mean the creation of the `Memory` object and using it for storing objects, and then passing pointers to it (indexes) to the Rust code, right?

BTW, I'm not even sure if the option (1) is possible at the moment. Most likely the allocators will differ.

**Comment by badboy** [comment]
Regarding (3): Yup, just put in some data, pass it as a pointer and let Rust construct the object, but not deallocate anything.

Option (1) is surely possible as long as both sides are absolutely identical (then again a minimal dumb allocator is not too hard to write, I do have such an example around as well)
