### ISSUE TITLE
Hellorust should be CC0 licensed.

### ISSUE THREAD

**Issue by badboy** [badboy/hellorust#23]
Since the content of the hellorust.com (and all examples) is intended to be copied freely, it would be better licensed CC0, with basically no restrictions.
This applies only to the code in the examples; libraries in use will have their own license.

We will track here the consent of all contributors:
Please drop a comment **here** if you consent or disagree. [Link to CC0 license](https://creativecommons.org/choose/zero/). Once we gather consent following will be merged: #22 

- [x] @booyaa 
- [x] @arkada38 
- [x] @tcr 
- [x] @Geal

**Comment by booyaa** [comment]
I consent to the license change!

**Comment by tcr** [comment]
I consent also!

**Comment by Geal** [comment]
I consent too

**Comment by arkada38** [comment]
I consent too

**Comment by badboy** [comment]
Thank you all!
