### ISSUE TITLE
Adding a couple of talks here

### ISSUE THREAD

**Issue by sendilkumarn** [badboy/hellorust#24]
Do things faster and better with WebAssembly 
by [Sendilkumarn](https://twitter.com/sendilkumarn) at [Codemotion Rome](https://rome2018.codemotionworld.com/speakers/) & [Amsterdam JS](https://www.meetup.com/AmsterdamJS/events/248340587/)

When: 2018-04-13, 2018-03-29

Material:

[Video](https://www.youtube.com/watch?v=V8tXLos5UKg&index=6&list=PLZzzYSK4x_uk9F65DVTIHFrnPFlxfxEbk)

**Comment by badboy** [comment]
Hey, thanks for that. Unfortunately I don't really have much time to maintain this anymore (I will take some time to mark it as such soon).
However, the Rust+Wasm WG is very active and [collects news in this issue](https://github.com/rust-lang-nursery/rust-wasm/issues/79).

**Comment by sendilkumarn** [comment]
Ha ha no issues, I am there
