### ISSUE TITLE
Vector element type in alloc function is unspecified

### ISSUE THREAD

**Issue by aochagavia** [badboy/hellorust#4]
It seems to me that Rust will pick a random type for the element of the vector you are creating in the `alloc` function:

https://github.com/badboy/hellorust/blob/3b0d1c9259c0e39a481b51764b053520b7a2fbd1/demos/factorial/factorial.rs#L6-L10

I am actually surprised that it compiles, since the element of the vector could be anything. Swapping line 7 by `let mut buf = Vec::<u64>::with_capacity(size);` or `let mut buf = Vec::<()>::with_capacity(size);` still compiles. I am wondering, which type is Rust choosing when you leave it up to inference? Are you sure it is `u8`?

**Comment by badboy** [comment]
I hope it’s `u8`, otherwise we’re wasting quite some memory. Will check later.

**Comment by badboy** [comment]
Puh, I looked at the code and say with confidence: Rust is doing alright.
The [function definition of `as_mut_ptr`](https://doc.rust-lang.org/std/primitive.slice.html#method.as_mut_ptr) is:

```rust
fn as_mut_ptr(&mut self) -> *mut T
```
Now this `T` is fixed to be `c_void` in our case, which [luckily is defined to be represented as an `u8`](https://doc.rust-lang.org/src/std/os/raw.rs.html#69-76) and therefore the right type here.
